// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: tmdb.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TMDBService service

type TMDBService interface {
	// Search RPC methods
	SearchCompanies(ctx context.Context, in *TMDBQueryOptions, opts ...client.CallOption) (*TMDBResponse, error)
	SearchMovies(ctx context.Context, in *TMDBQueryYearOptions, opts ...client.CallOption) (*TMDBResponse, error)
	SearchTV(ctx context.Context, in *TMDBQueryYearOptions, opts ...client.CallOption) (*TMDBResponse, error)
	// Movies RPC methods
	GetMovieInformation(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetMovieAlternativeTitles(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetMovieChanges(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetMovieCredits(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetMovieExternalIDs(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetMovieImages(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetMovieKeywords(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetMovieReleaseDates(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetMovieVideos(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetMovieTranslations(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	// Series RPC methods
	GetTVInformation(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVChanges(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVCredits(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVExternalIDs(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVImages(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVKeywords(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVVideos(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVTranslations(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	// Series Seasons RPC methods
	GetTVSeasonInformation(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVSeasonChanges(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVSeasonCredits(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVSeasonExternalIDs(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVSeasonImages(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVSeasonVideos(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error)
	// Series Episodes RPC methods
	GetTVEpisodeInformation(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVEpisodeChanges(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVEpisodeCredits(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVEpisodeExternalIDs(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVEpisodeImages(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVEpisodeTranslations(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error)
	GetTVEpisodeVideos(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error)
}

type tMDBService struct {
	c    client.Client
	name string
}

func NewTMDBService(name string, c client.Client) TMDBService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &tMDBService{
		c:    c,
		name: name,
	}
}

func (c *tMDBService) SearchCompanies(ctx context.Context, in *TMDBQueryOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.SearchCompanies", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) SearchMovies(ctx context.Context, in *TMDBQueryYearOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.SearchMovies", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) SearchTV(ctx context.Context, in *TMDBQueryYearOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.SearchTV", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieInformation(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieInformation", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieAlternativeTitles(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieAlternativeTitles", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieChanges(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieChanges", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieCredits(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieCredits", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieExternalIDs(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieExternalIDs", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieImages(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieImages", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieKeywords(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieKeywords", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieReleaseDates(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieReleaseDates", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieVideos(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieVideos", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetMovieTranslations(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetMovieTranslations", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVInformation(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVInformation", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVChanges(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVChanges", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVCredits(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVCredits", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVExternalIDs(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVExternalIDs", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVImages(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVImages", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVKeywords(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVKeywords", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVVideos(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVVideos", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVTranslations(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVTranslations", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVSeasonInformation(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVSeasonInformation", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVSeasonChanges(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVSeasonChanges", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVSeasonCredits(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVSeasonCredits", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVSeasonExternalIDs(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVSeasonExternalIDs", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVSeasonImages(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVSeasonImages", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVSeasonVideos(ctx context.Context, in *TMDBSeason, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVSeasonVideos", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVEpisodeInformation(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVEpisodeInformation", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVEpisodeChanges(ctx context.Context, in *TMDBIDOptions, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVEpisodeChanges", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVEpisodeCredits(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVEpisodeCredits", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVEpisodeExternalIDs(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVEpisodeExternalIDs", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVEpisodeImages(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVEpisodeImages", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVEpisodeTranslations(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVEpisodeTranslations", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMDBService) GetTVEpisodeVideos(ctx context.Context, in *TMDBSeasonEpisode, opts ...client.CallOption) (*TMDBResponse, error) {
	req := c.c.NewRequest(c.name, "TMDBService.GetTVEpisodeVideos", in)
	out := new(TMDBResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TMDBService service

type TMDBServiceHandler interface {
	// Search RPC methods
	SearchCompanies(context.Context, *TMDBQueryOptions, *TMDBResponse) error
	SearchMovies(context.Context, *TMDBQueryYearOptions, *TMDBResponse) error
	SearchTV(context.Context, *TMDBQueryYearOptions, *TMDBResponse) error
	// Movies RPC methods
	GetMovieInformation(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetMovieAlternativeTitles(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetMovieChanges(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetMovieCredits(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetMovieExternalIDs(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetMovieImages(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetMovieKeywords(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetMovieReleaseDates(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetMovieVideos(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetMovieTranslations(context.Context, *TMDBIDOptions, *TMDBResponse) error
	// Series RPC methods
	GetTVInformation(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetTVChanges(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetTVCredits(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetTVExternalIDs(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetTVImages(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetTVKeywords(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetTVVideos(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetTVTranslations(context.Context, *TMDBIDOptions, *TMDBResponse) error
	// Series Seasons RPC methods
	GetTVSeasonInformation(context.Context, *TMDBSeason, *TMDBResponse) error
	GetTVSeasonChanges(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetTVSeasonCredits(context.Context, *TMDBSeason, *TMDBResponse) error
	GetTVSeasonExternalIDs(context.Context, *TMDBSeason, *TMDBResponse) error
	GetTVSeasonImages(context.Context, *TMDBSeason, *TMDBResponse) error
	GetTVSeasonVideos(context.Context, *TMDBSeason, *TMDBResponse) error
	// Series Episodes RPC methods
	GetTVEpisodeInformation(context.Context, *TMDBSeasonEpisode, *TMDBResponse) error
	GetTVEpisodeChanges(context.Context, *TMDBIDOptions, *TMDBResponse) error
	GetTVEpisodeCredits(context.Context, *TMDBSeasonEpisode, *TMDBResponse) error
	GetTVEpisodeExternalIDs(context.Context, *TMDBSeasonEpisode, *TMDBResponse) error
	GetTVEpisodeImages(context.Context, *TMDBSeasonEpisode, *TMDBResponse) error
	GetTVEpisodeTranslations(context.Context, *TMDBSeasonEpisode, *TMDBResponse) error
	GetTVEpisodeVideos(context.Context, *TMDBSeasonEpisode, *TMDBResponse) error
}

func RegisterTMDBServiceHandler(s server.Server, hdlr TMDBServiceHandler, opts ...server.HandlerOption) error {
	type tMDBService interface {
		SearchCompanies(ctx context.Context, in *TMDBQueryOptions, out *TMDBResponse) error
		SearchMovies(ctx context.Context, in *TMDBQueryYearOptions, out *TMDBResponse) error
		SearchTV(ctx context.Context, in *TMDBQueryYearOptions, out *TMDBResponse) error
		GetMovieInformation(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetMovieAlternativeTitles(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetMovieChanges(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetMovieCredits(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetMovieExternalIDs(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetMovieImages(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetMovieKeywords(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetMovieReleaseDates(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetMovieVideos(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetMovieTranslations(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVInformation(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVChanges(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVCredits(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVExternalIDs(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVImages(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVKeywords(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVVideos(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVTranslations(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVSeasonInformation(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error
		GetTVSeasonChanges(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVSeasonCredits(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error
		GetTVSeasonExternalIDs(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error
		GetTVSeasonImages(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error
		GetTVSeasonVideos(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error
		GetTVEpisodeInformation(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error
		GetTVEpisodeChanges(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error
		GetTVEpisodeCredits(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error
		GetTVEpisodeExternalIDs(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error
		GetTVEpisodeImages(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error
		GetTVEpisodeTranslations(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error
		GetTVEpisodeVideos(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error
	}
	type TMDBService struct {
		tMDBService
	}
	h := &tMDBServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TMDBService{h}, opts...))
}

type tMDBServiceHandler struct {
	TMDBServiceHandler
}

func (h *tMDBServiceHandler) SearchCompanies(ctx context.Context, in *TMDBQueryOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.SearchCompanies(ctx, in, out)
}

func (h *tMDBServiceHandler) SearchMovies(ctx context.Context, in *TMDBQueryYearOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.SearchMovies(ctx, in, out)
}

func (h *tMDBServiceHandler) SearchTV(ctx context.Context, in *TMDBQueryYearOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.SearchTV(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieInformation(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieInformation(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieAlternativeTitles(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieAlternativeTitles(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieChanges(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieChanges(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieCredits(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieCredits(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieExternalIDs(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieExternalIDs(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieImages(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieImages(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieKeywords(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieKeywords(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieReleaseDates(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieReleaseDates(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieVideos(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieVideos(ctx, in, out)
}

func (h *tMDBServiceHandler) GetMovieTranslations(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetMovieTranslations(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVInformation(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVInformation(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVChanges(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVChanges(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVCredits(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVCredits(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVExternalIDs(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVExternalIDs(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVImages(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVImages(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVKeywords(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVKeywords(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVVideos(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVVideos(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVTranslations(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVTranslations(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVSeasonInformation(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVSeasonInformation(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVSeasonChanges(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVSeasonChanges(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVSeasonCredits(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVSeasonCredits(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVSeasonExternalIDs(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVSeasonExternalIDs(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVSeasonImages(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVSeasonImages(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVSeasonVideos(ctx context.Context, in *TMDBSeason, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVSeasonVideos(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVEpisodeInformation(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVEpisodeInformation(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVEpisodeChanges(ctx context.Context, in *TMDBIDOptions, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVEpisodeChanges(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVEpisodeCredits(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVEpisodeCredits(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVEpisodeExternalIDs(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVEpisodeExternalIDs(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVEpisodeImages(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVEpisodeImages(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVEpisodeTranslations(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVEpisodeTranslations(ctx, in, out)
}

func (h *tMDBServiceHandler) GetTVEpisodeVideos(ctx context.Context, in *TMDBSeasonEpisode, out *TMDBResponse) error {
	return h.TMDBServiceHandler.GetTVEpisodeVideos(ctx, in, out)
}
